server:
  port: 8080


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employeemanager
    #    url: jdbc:postgresql://eleap-db.cog31bemqyld.eu-central-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL94Dialect
